[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints= { sepolia = "https://eth-sepolia.g.alchemy.com/v2/vlZhYIdAxg3G6bCgUClc_vFN9ovDQdte", arb_sepolia = "https://arb-sepolia.g.alchemy.com/v2/vlZhYIdAxg3G6bCgUClc_vFN9ovDQdte" }

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@ccip/=lib/ccip/",
    "@chainlink-local/=lib/chainlink-local/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
